xcursorgen config.in	cursors/arrow
xcursorgen config.in	cursors/based_arrow_up
xcursorgen config.in    cursors/bd_double_arrow
xcursorgen config.in	cursors/bottom_left_corner
xcursorgen config.in	cursors/bottom_right_corner
xcursorgen config.in	cursors/bottom_side
xcursorgen config.in	cursors/circle
xcursorgen config.in	cursors/copy
xcursorgen config.in	cursors/crossed_circle
xcursorgen config.in	cursors/crosshair
xcursorgen config.in	cursors/double_arrow
xcursorgen config.in	cursors/draft_large
xcursorgen config.in 	cursors/draft_small
xcursorgen config.in	cursors/fd_double_arrow
xcursorgen config.in	cursors/fleur
xcursorgen config.in	cursors/h_double_arrow
xcursorgen config.in	cursors/hand
xcursorgen config.in	cursors/hand1
xcursorgen config.in	cursors/hand2
xcursorgen config.in	cursors/left_ptr
xcursorgen config.in	cursors/left_ptr_watch
xcursorgen config.in	cursors/left_side
xcursorgen config.in	cursors/link
xcursorgen config.in	cursors/question_arrow
xcursorgen config.in	cursors/right_ptr
xcursorgen config.in	cursors/right_side
xcursorgen config.in	cursors/sb_down_arrow
xcursorgen config.in	cursors/sb_h_double_arrow
xcursorgen config.in 	cursors/sb_left_arrow
xcursorgen config.in	cursors/sb_right_arrow
xcursorgen config.in	cursors/sb_up_arrow
xcursorgen config.in	cursors/sb_v_double_arrow
xcursorgen config.in	cursors/top_left_arrow
xcursorgen config.in	cursors/top_left_corner
xcursorgen config.in	cursors/top_right_corner
xcursorgen config.in	cursors/top_side
xcursorgen config.in	cursors/v_double_arrow
xcursorgen config.in    cursors/watch
xcursorgen config.in	cursors/X_cursor
xcursorgen config.in	cursors/00008160000006810000408080010102                            
xcursorgen config.in	cursors/028006030e0e7ebffc7f7070c0600140                         
xcursorgen config.in	cursors/03b6e0fcb3499374a867c041f52298f0                             
xcursorgen config.in	cursors/08e8e1c95fe2fc01f976f1e063a24ccd                              
xcursorgen config.in	cursors/14fef782d02440884392942c11205230                            
xcursorgen config.in	cursors/2870a09082c103050810ffdffffe0204                              
xcursorgen config.in	cursors/3ecb610c1bf2410f44200f48c40d3599                               
xcursorgen config.in	cursors/4498f0e0c1937ffe01fd06f973665830                                      
xcursorgen config.in	cursors/6407b0e94181790501fd1e167b474872                                      
xcursorgen config.in	cursors/640fb0e74195791501fd1ed57b41487f                                       
xcursorgen config.in	cursors/9d800788f1b08800ae810202380a0822                                   
xcursorgen config.in	cursors/c7088f0f3e6c8088236ef8e1e3e70000                            
xcursorgen config.in	cursors/cursors/d9ce0ab605698f320427677b458ad60b                             
xcursorgen config.in	cursors/e29285e634086352946a0e7090d73106                                    
xcursorgen config.in	cursors/fcf1c3c7cd4491d801f1e1c78f100000

xcursorgen config.in cursors/sb_v_double_arrow
xcursorgen config.in cursors/sb_h_double_arrow
xcursorgen config.in cursors/crossed_circle  
xcursorgen config.in cursors/left_ptr_watch   
xcursorgen config.in cursors/h_double_arrow
xcursorgen config.in cursors/v_double_arrow 
xcursorgen config.in cursors/left_ptr_watch 
xcursorgen config.in cursors/fleur 
xcursorgen config.in  cursors/copy          
xcursorgen config.in   cursors/link  
xcursorgen config.in cursors/hand1
xcursorgen config.in cursors/top_left_corner
xcursorgen config.in cursors/question_arrow
xcursorgen config.in cursors/hand
xcursorgen config.in cursors/top_right_corner
